- include_vars: variables.yml

- name: Wait until apt-get process is not running
  shell: ps -ax | grep apt-get | wc -l
  register: result
  until: result.stdout | int <= 2
  retries: 5
  delay: 15
  ignore_errors: yes

- file: path="{{item}}" state=absent
  with_items:
    - /var/lib/apt/lists/lock
    - /var/lib/dpkg/lock
    - /var/lib/dpkg/lock-frontend

- name: apt-get update
  apt: update_cache=yes


# update /etc/security/limit.conf values
- pam_limits:
    domain: '*'
    limit_type: soft
    limit_item: nofile
    value: 999999

- pam_limits:
    domain: '*'
    limit_type: hard
    limit_item: nofile
    value: 999999